// <auto-generated />
namespace TekConf.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShortDescriptionConference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShortDescriptionConference));
        
        string IMigrationMetadata.Id
        {
            get { return "201608262104552_ShortDescriptionConference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
