// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ConferencesIO.UI.iOS
{
	public partial class SessionsListViewController : UIViewController
	{
		public SessionsListViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
