// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ConferencesIO.RemoteData.v1;

namespace ConferencesIO.UI.iOS
{
	public partial class SpeakerDetailViewController : UIViewController
	{
		private RemoteDataRepository _client;
		private string _baseUrl = "http://conferencesioapi.azurewebsites.net/v1/";
		public string SpeakerSlug { get; set; }

		public SpeakerDetailViewController () : base()
		{
			
		}

		public SpeakerDetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
