// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using TekConf.RemoteData.v1;

namespace TekConf.UI.iOS
{
	public partial class SessionDetailViewController : UIViewController
	{
		private RemoteDataRepository _client;
		//private string _baseUrl = "http://conferencesioapi.azurewebsites.net/v1/";
		private string _baseUrl = "http://192.168.1.105/TekConf.UI.Api";

		public string SessionSlug { get; set; }

		static bool UserInterfaceIdiomIsPhone {
			get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone; }
		}

		public SessionDetailViewController () : base()
		{
			
		}

		public SessionDetailViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);

			_client = new RemoteDataRepository (_baseUrl);

			var loading = new UIAlertView ("Downloading Session", "Please wait...", null, null, null);

			loading.Show ();

			var indicator = new UIActivityIndicatorView (UIActivityIndicatorViewStyle.WhiteLarge); 
			indicator.Center = new System.Drawing.PointF (loading.Bounds.Width / 2, loading.Bounds.Size.Height - 40); 
			indicator.StartAnimating (); 
			loading.AddSubview (indicator);

			_client.GetSession ("thatconference-2013", this.SessionSlug, session => 
			{ 
				InvokeOnMainThread (() => 
				{ 
					//new UIAlertView ("Session", session.title, null, "Ok", null).Show ();
					this.sessionTitleLabel.Text = session.title;
					this.sessionEndLabel.Text = session.end.ToString ();
					this.sessionStartLabel.Text = session.start.ToString();
					this.sessionTwitterHashTagLabel.Text = session.twitterHashTag;
					loading.DismissWithClickedButtonIndex (0, true); 
				}
				);
			}
			);

			// Perform any additional setup after loading the view, typically from a nib.
			
			//this.TableView.Source = new DataSource (this);
			
//			if (!UserInterfaceIdiomIsPhone) {
//				this.TableView.SelectRow (
//					NSIndexPath.FromRowSection (0, 0),
//					false,
//					UITableViewScrollPosition.Middle
//				);
//			}
		}
	
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			var backgroundImage = UIImage.FromBundle(@"images/appview/bg");
			//this.View.BackgroundColor = UIColor.FromPatternImage(backgroundImage);
		}	
	}
}
