// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Linq;
using System.Threading;
using System.Collections.Generic;
using ConferencesIO.RemoteData.v1;
using ConferencesIO.RemoteData.Dtos.v1;

namespace ConferencesIO.UI.iOS
{
	public partial class SessionsViewController : UITableViewController
	{




		public SessionsViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			var backgroundImage = UIImage.FromBundle(@"images/appview/bg");
			//this.View.BackgroundColor = UIColor.FromPatternImage(backgroundImage);
		}



	}
}
