#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TekConf.UI.Android.Resource", IsApplication=true)]

namespace TekConf.UI.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_disclosure = TekConf.UI.Android.Resource.Drawable.dialog_disclosure;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_expander_ic_minimized = TekConf.UI.Android.Resource.Drawable.dialog_expander_ic_minimized;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_icon = TekConf.UI.Android.Resource.Drawable.dialog_icon;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_dark = TekConf.UI.Android.Resource.Drawable.dialog_spinner_default_holo_dark;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_light = TekConf.UI.Android.Resource.Drawable.dialog_spinner_default_holo_light;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_BoolField = TekConf.UI.Android.Resource.Id.dialog_BoolField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Button = TekConf.UI.Android.Resource.Id.dialog_Button;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_DisclosureField = TekConf.UI.Android.Resource.Id.dialog_DisclosureField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_HtmlField = TekConf.UI.Android.Resource.Id.dialog_HtmlField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageLeft = TekConf.UI.Android.Resource.Id.dialog_ImageLeft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageRight = TekConf.UI.Android.Resource.Id.dialog_ImageRight;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelField = TekConf.UI.Android.Resource.Id.dialog_LabelField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelPercentageField = TekConf.UI.Android.Resource.Id.dialog_LabelPercentageField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelSubtextField = TekConf.UI.Android.Resource.Id.dialog_LabelSubtextField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Panel = TekConf.UI.Android.Resource.Id.dialog_Panel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_RadioButtonList = TekConf.UI.Android.Resource.Id.dialog_RadioButtonList;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_SliderField = TekConf.UI.Android.Resource.Id.dialog_SliderField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Spinner = TekConf.UI.Android.Resource.Id.dialog_Spinner;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ValueField = TekConf.UI.Android.Resource.Id.dialog_ValueField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.iFormFieldValue = TekConf.UI.Android.Resource.Id.iFormFieldValue;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_achievements = TekConf.UI.Android.Resource.Layout.dialog_achievements;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldleft = TekConf.UI.Android.Resource.Layout.dialog_boolfieldleft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldright = TekConf.UI.Android.Resource.Layout.dialog_boolfieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubleft = TekConf.UI.Android.Resource.Layout.dialog_boolfieldsubleft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubright = TekConf.UI.Android.Resource.Layout.dialog_boolfieldsubright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_button = TekConf.UI.Android.Resource.Layout.dialog_button;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_datefield = TekConf.UI.Android.Resource.Layout.dialog_datefield;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_fieldsetlabel = TekConf.UI.Android.Resource.Layout.dialog_fieldsetlabel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_floatimage = TekConf.UI.Android.Resource.Layout.dialog_floatimage;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_html = TekConf.UI.Android.Resource.Layout.dialog_html;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labeldisclosure = TekConf.UI.Android.Resource.Layout.dialog_labeldisclosure;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldbelow = TekConf.UI.Android.Resource.Layout.dialog_labelfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldright = TekConf.UI.Android.Resource.Layout.dialog_labelfieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_multiline_labelfieldbelow = TekConf.UI.Android.Resource.Layout.dialog_multiline_labelfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_onofffieldright = TekConf.UI.Android.Resource.Layout.dialog_onofffieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_panel = TekConf.UI.Android.Resource.Layout.dialog_panel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_root = TekConf.UI.Android.Resource.Layout.dialog_root;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlist = TekConf.UI.Android.Resource.Layout.dialog_selectlist;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlistfield = TekConf.UI.Android.Resource.Layout.dialog_selectlistfield;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textarea = TekConf.UI.Android.Resource.Layout.dialog_textarea;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldbelow = TekConf.UI.Android.Resource.Layout.dialog_textfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldright = TekConf.UI.Android.Resource.Layout.dialog_textfieldright;
			Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = TekConf.UI.Android.Resource.String.ApplicationName;
			Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = TekConf.UI.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Calendar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_2_icon16 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar_2_icon24 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar_2_icon32 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int clock_icon16 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int clock_icon24 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int clock_icon32 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int clock_icon48 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cog_icon16 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cog_icon24 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cog_icon32 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cog_icon48 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int connect_icon24 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int connect_icon32 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dialog_disclosure = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dialog_expander_ic_minimized = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dialog_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dialog_spinner_default_holo_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int dialog_spinner_default_holo_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int facebook_001 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Gear = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Google_Plus_001 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Group = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Heart = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int heart_empty_icon24 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int heart_empty_icon32 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int heart_icon24 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int heart_icon32 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Magnify = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Refresh = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int refresh_icon24 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int refresh_icon32 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int splash = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int star_fav_empty_icon24 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int star_fav_empty_icon32 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int star_fav_icon24 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int star_fav_icon32 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int TekConf = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int TransparentIcon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Twitter_001 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int user_icon24 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int user_icon32 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int users_icon24 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int users_icon32 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int zoom_icon24 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int zoom_icon32 = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001d
			public const int DisplayTextLabel = 2131034141;
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int dialog_BoolField = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int dialog_Button = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int dialog_DisclosureField = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int dialog_HtmlField = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int dialog_ImageLeft = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int dialog_ImageRight = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int dialog_LabelField = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int dialog_LabelPercentageField = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int dialog_LabelSubtextField = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int dialog_Panel = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int dialog_RadioButtonList = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int dialog_SliderField = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int dialog_Spinner = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int dialog_ValueField = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int facebookGoogleRow = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int facebookLoginButton = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int googlePlusLoginButton = 2131034140;
			
			// aapt resource value: 0x7f05000f
			public const int iFormFieldValue = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int loggedInState = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int loggedInStateLayout = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int loginName = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int loginNameLayout = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int logoutButton = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int logoutButtonLayout = 2131034133;
			
			// aapt resource value: 0x7f05001f
			public const int menu_favorite = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int menu_refresh = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int menu_sessions = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int menu_settings = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int menu_speakers = 2131034146;
			
			// aapt resource value: 0x7f050010
			public const int tableLayout1 = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int tekConfLoginButton = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int tekConfTwitterRow = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int twitterLoginButton = 2131034137;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConferenceDetailView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConferenceSessionsView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ConferencesListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_achievements = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldleft = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_boolfieldright = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_boolfieldsubleft = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_boolfieldsubright = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_button = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_datefield = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_fieldsetlabel = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_floatimage = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_html = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_labeldisclosure = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_labelfieldbelow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_labelfieldright = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_multiline_labelfieldbelow = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_onofffieldright = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_panel = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_root = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_selectlist = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_selectlistfield = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int dialog_textarea = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int dialog_textfieldbelow = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int dialog_textfieldright = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Item_Conference = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Item_Session = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int SessionDetailView = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int SettingsView = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int SpinnerItem = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int SplashScreen = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ConferenceDetailActionItems = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ConferencesListActionItems = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int SessionDetailActionItems = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
