#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TekConf.Core.Droid.Resource", IsApplication=false)]

namespace TekConf.Core.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public static int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int dialog_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int dialog_spinner_default_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int dialog_spinner_default_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int splash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public static int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050005
			public static int dialog_BoolField = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int dialog_Button = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public static int dialog_DisclosureField = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public static int dialog_HtmlField = 2131034122;
			
			// aapt resource value: 0x7f050008
			public static int dialog_ImageLeft = 2131034120;
			
			// aapt resource value: 0x7f050003
			public static int dialog_ImageRight = 2131034115;
			
			// aapt resource value: 0x7f050001
			public static int dialog_LabelField = 2131034113;
			
			// aapt resource value: 0x7f050004
			public static int dialog_LabelPercentageField = 2131034116;
			
			// aapt resource value: 0x7f050002
			public static int dialog_LabelSubtextField = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public static int dialog_Panel = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int dialog_RadioButtonList = 2131034125;
			
			// aapt resource value: 0x7f050009
			public static int dialog_SliderField = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public static int dialog_Spinner = 2131034126;
			
			// aapt resource value: 0x7f050007
			public static int dialog_ValueField = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public static int iFormFieldValue = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int dialog_html = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int dialog_labeldisclosure = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int dialog_labelfieldbelow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int dialog_labelfieldright = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int dialog_multiline_labelfieldbelow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int dialog_onofffieldright = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int dialog_panel = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int dialog_root = 2130903056;
			
			// aapt resource value: 0x7f030011
			public static int dialog_selectlist = 2130903057;
			
			// aapt resource value: 0x7f030012
			public static int dialog_selectlistfield = 2130903058;
			
			// aapt resource value: 0x7f030013
			public static int dialog_textarea = 2130903059;
			
			// aapt resource value: 0x7f030014
			public static int dialog_textfieldbelow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public static int dialog_textfieldright = 2130903061;
			
			// aapt resource value: 0x7f030016
			public static int FirstView = 2130903062;
			
			// aapt resource value: 0x7f030017
			public static int SplashScreen = 2130903063;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public static int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public static int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public static int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public static int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
